### PR TITLE
Back end front end

### PR DESCRIPTION
**Pull request by gonjavi**

### CODE REVIEW

**Comment by gonjavi** [comment]
> Hi @gonjavi great start to this project  are you working alone on this? If yes why?
> 
> Please fix the error below and also use a partial for the form and call it for both the signup and update
> 
> 
> Submit for re-review when you are done

Yes, I am working alone this project, we couldn't work together this one maybe the next one

**Comment by Oghenebrume50** [comment]
@gonjavi from what I can see this is a collaborative project, is there a particular reason you guys are working separately on this one?

**Comment by gonjavi** [comment]
because he was having some issues so move forward, so we couldn't work synchronize, so we spoke we are going to do it for the next one

**Comment by gonjavi** [comment]
no, We didn't. But if it is not possible, I speak to him to do it again.

**Comment by Oghenebrume50** [comment]
This kind of decisions should go through  student success, that way they can help your partner with any challenge he is facing. Please can you guys do that? As a partner your duty is to look after him, with the support of student success, we are one big family 🤗🤗

**Pull request merged**
